'use client'
import { Metadata } from "next";
import Providers from './store/provider'
import {store} from "./store";

export const metadata: Metadata = {
	title: "My App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Providers store={store}>
					{children}
				</Providers>
			</body>
		</html>
	);
}
