'use client'
import { Metadata } from "next";
import Providers from './store/provider'
import {store} from "./store";
import style from './layout.module.scss'

export const metadata: Metadata = {
	title: "My App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={style.body}>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}
